### ISSUE TITLE
Footnote xml:id

### ISSUE THREAD

**Issue by pml1951** [TU-plogan/encyclopedia-project#23]
change all footnote referent and footnote text xml:id's to make them unique.

**Comment by pml1951** [comment]
`<pb>` problem: All note` xml:id`'s are keeping the first page # as a base, leading to non-unique names for later pages.

**Comment by Siotto** [comment]
for the problem of the xml:id of a multiple-page file with the note changed accordingly to the page number  I need the entry file name.

**Comment by Siotto** [comment]
the other issue has been solved.
now the format of a note is like in this example:
<ref xml:id="eb11-22-r-0819_01p0819-r1" target="eb11-22-r-0819_01p0819-n1">1</ref><note xml:id="eb11-22-r-0819_01p0819-n1" n="1">...</note>

name of the file (eb11-22-r-819_01) number of page (p0819) index code of the note (r1 and n1)

**Comment by Siotto** [comment]
If you find the solution appropriate, close the issue.

**Comment by pml1951** [comment]
This looks right to me. We'll test it on the next output.
