### ISSUE TITLE
Entry segmenting: "Radioactivity"

### ISSUE THREAD

**Issue by pml1951** [TU-plogan/encyclopedia-project#29]
Bad entry segmenting:

`eb11-22-r-0797_01.xml `is part of "Radioactivity" entry, `eb11-22-r-0793_02.xml`. Script split it in the middle of a formula, on line beginning "R= ... ". 
```
<p><label> R - </label>
	n <sub> Q </sub> (ae-W+be-W+cc-W), , _Xj__ 1 _—Xi____X]Xg_ ^ <sup> eſC a </sup> 
``````

**Comment by Siotto** [comment]
solved 03-19-2017
