### ISSUE TITLE
<div> errors

### ISSUE THREAD

**Issue by pml1951** [TU-plogan/encyclopedia-project#30]
We are still getting many incorrect `<div>` elements, and they cause a cascade of more validation problems. One file (railroads) `eb11-22-r-019_01` included 19 separate `<div>` codes, when it should only have one.

The most frequent pattern in the addition of a `<div>` after a `<pb>.` It doesn't add the closing tag, so we get an xml error. Here's an example, from `eb11-22-r-0929_03`. 

```
... Lawrence was rebuilt</p>

<pb n="eb11-22-r-0930"/>
<div> <p> in 1839 with the exception ...
```
In other cases, it inserts the pagebreak fine, without an extra `<div>`. Here's an example from `eb11-22-r-0930_02`.
```
 ... from their surface congeners. Rays, as is </p>

<pb n="eb11-22-r-0931"/>
<p> indicated by their shape, are bottom-fishes, ...
```

**Comment by Siotto** [comment]
solved 03-19-2017
