### ISSUE TITLE
Error segmenting RATISBONNE

### ISSUE THREAD

**Issue by pml1951** [TU-plogan/encyclopedia-project#39]
Note that we get an H3 again ...

In eb11-22-r-0916_04:

`by O. Kirn in Herzog-Hauck, Realencyk. xvi. (1905).</p><h3> RATISBONNE, LOUIS GUSTAVE FORTUNfi (1827-1900),</h3><p> French man of letters, `

**Comment by Siotto** [comment]
solved 03-19-2017
